"""Persistence boundary: SQLite is the local adapter, not a cloud DB assumption."""
from typing import Protocol, Callable


class Repository(Protocol):
    def create_session(self, identity: dict, *, expires_at: int, now: int) -> str: ...
    def authenticate(self, credential: str, *, now: int) -> dict: ...
    def archive_round(self, identity: dict, round_id: str, period: str, payload: dict,
                      contributions: dict, jobs: list | Callable, *, now: int,
                      reducer: Callable | None = None, receipt_builder: Callable | None = None,
                      period_info: dict | Callable | None = None, close_builder: Callable | None = None,
                      late_arrival: bool = False, clock: Callable | None = None) -> dict: ...
    def totals(self, app_id: str, online: bool, period: str) -> dict: ...
    def claim_job(self, *, now: int, lease_seconds: int = 30) -> dict | None: ...
    def finish_job(self, job_id: int, lease_token: str, *, now: int) -> bool: ...
    def retry_job(self, job_id: int, lease_token: str, error: str, *, now: int, delay: int) -> bool: ...
    def fail_job(self, job_id: int, lease_token: str, error: str, *, now: int) -> bool: ...
    def rollover(self, app_id: str, online: bool, period: dict, *, now: int, close_builder: Callable) -> None: ...
    def outbox_status(self) -> dict: ...
